### ISSUE TITLE
Project is outdated, please update the endpoints are latest version.

### ISSUE THREAD

**Issue by Natgho** [Salamek/instagram-basic-display-python#10]
You should add version of URL for all endpoints;
![image](https://user-images.githubusercontent.com/6623948/221699181-361a8683-8d1e-4dee-bc6c-6e92524ab405.png)

**Comment by Salamek** [comment]
Any docs to this? I don't see anything in docs about this https://developers.facebook.com/docs/instagram-basic-display-api/reference/oauth-authorize#reading

**Comment by stolenvw** [comment]
leaving it unversioned uses the version set in the app dashboard Upgrade API Version card under Settings > Advanced.

**Comment by Salamek** [comment]
I have added a option to specify version in `InstagramBasicDisplay` constructor, this will allow you to force required version in code + also allows fallback to use configured graph version in api settings.
Let me know if that is ok for you, ill make release after.
