### ISSUE TITLE
No module named 'instagram_basic_display' after installing it with pip3

### ISSUE THREAD

**Issue by Tatuck** [Salamek/instagram-basic-display-python#2]
Hello! I have tried to use it but every time I open the file it says: 

```
from instagram_basic_display.InstagramBasicDisplay import InstagramBasicDisplay
ModuleNotFoundError: No module named 'instagram_basic_display'
```

And I don't know what to do, I tried installing it again but it keeps me saying this error, any help?

Thanks

**Comment by Salamek** [comment]
How are you running it? are you using python3 to run it?
Some distros use python2 as default python, try to use:
```
python3 my_file_name.py
```

**Comment by Salamek** [comment]
@Tatuck well i guess this is resolved then?
Reopen if not...
