### ISSUE TITLE
NameError: name 'request' is not defined

### ISSUE THREAD

**Issue by Tatuck** [Salamek/instagram-basic-display-python#3]
Hello! I tried to use the module, but every time I try to use it it shows me this error: NameError: name 'request' is not defined

I tried using: import requests, but it doesn't work.

The code i am trying to use is:

```
from instagram_basic_display.InstagramBasicDisplay import InstagramBasicDisplay


instagram_basic_display = InstagramBasicDisplay(app_id='app-id', app_secret='app-secret', redirect_url='https://developers.facebook.com/sa/apps/app-id')

print(instagram_basic_display.get_login_url()) # Returns login URL you need to follow

# Get the OAuth callback code
code = request.args.get('code') <- HERE IS WHERE IT SHOWS THE ERROR

# Get the short lived access token (valid for 1 hour)
short_lived_token = instagram_basic_display.get_o_auth_token(code)

# Exchange this token for a long lived token (valid for 60 days)
long_lived_token = instagram_basic_display.get_long_lived_token(short_lived_token.get('access_token'))

print('Your token is: {}' .format(long_lived_token.access_token))

# Set user access token
instagram_basic_display.set_access_token(long_lived_token.access_token)

# Get the users profile
profile = instagram_basic_display.get_user_profile()

print(profile)
```

Thanks

**Comment by Salamek** [comment]
A line `request.args.get('code')` is just example line to get `code` argument from GET request... use what your framework uses...

**Comment by Tatuck** [comment]
> A line `request.args.get('code')` is just example line to get `code` argument from GET request... use what your framework uses...

I don't know what does my framework uses. I am new in python. Do you know what should I use?

**Comment by Salamek** [comment]
@Tatuck  well you need some kind of webserver to handle login redirect url from instagram, that is where `code` arg is...
(or you can manually extract it and add it temporary to the source code).
I personally use Flask as a web framework for python, lot of ppl is using Django...
What is your goal with this library?

**Comment by Tatuck** [comment]
I tried to use flask but now it shows me this error:

```
Traceback (most recent call last):
  File "instagram-basic-api-prueba.py", line 9, in <module>
    code = request.args.get('code')
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\Users\marco\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

My goal is to get user media

**Comment by Salamek** [comment]
@Tatuck well i suggest that you read up Flask doc https://flask.palletsprojects.com/ and check their [examples](https://flask.palletsprojects.com/en/1.1.x/quickstart/#a-minimal-application) how to run simple web app...

**Comment by Tatuck** [comment]
This is really difficult, I think I am going to quit it. Thanks anyway
