### ISSUE TITLE
Do you have any recommendations for refreshing the long lived access token before the 60 days is up?

### ISSUE THREAD

**Issue by Natetronn** [Salamek/instagram-basic-display-python#6]
First off, thanks for the lib! Secondly, not really an "issue" per se, hope you don't mind me picking your brain:

Do you have any recommendations for refreshing the long lived access token before the 60 days is up?

I was considering using [Schedule](https://pypi.org/project/schedule/) but, was curious what you're using?

Thanks again...

**Comment by Salamek** [comment]
Well personally in my API "proxy" app build on top of this library, i'm using [celery](https://docs.celeryproject.org/en/stable/) and i'm also checking expiration on each external request. Celery was my choice because i'm using it in all my other projects... but it may be overkill for you...

**Comment by Natetronn** [comment]
Thanks for the reply. I hadn't heard of celery before. Yeah, looks like there's quite a bit there. Might be more than I need and quite a bit more than I'm willing to sift through too. 

Of course, I honestly can't believe their (Instagram's) API isn't a bit more friendly and that I have to submit a screencast before even getting access. This is but a simple Single Page Website with 8-10 of the latest image from a single profile.

So you're just querying the `get_long_lived_token(access_token)` every time to get the `expires_in`, then if it's close to expiring you hit the `refresh_token(access_token)` again?

**Comment by Salamek** [comment]
Yea FB changed Instagram API for "privacy" and "security" resons to this mess...
I'm querying `get_long_lived_token` only when needed, i cache all expiration dates and other stuff in database so i'm checking against my database and when is token about to expire then i'm calling `get_long_lived_token` and store data in database again

```python
# User database table
class User(BaseTable):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    api_token = db.Column(GUID(), nullable=False, index=True, unique=True, default=uuid.uuid4) #My own api token to allow my apps access instagram data
    user_id = db.Column(db.BigInteger, nullable=False)  # Instagram user_id
    access_token = db.Column(db.Unicode(255), nullable=False)
    access_token_expires = db.Column(db.DateTime, nullable=False)
```

I could release my instagram "proxy" API app under GPL on GitHub, but it needs some work before i can do that and i need to do some paid work first :)  Or i could allow other PPL to use it, then you could fetch data by simply logging into the Instagram account and calling:

```
r = requests.get('https://URL_I_DONT_WANT_TO_DISCLOSE_YET/api/get-user-media/API_TOKEN?limit=8')
        return r.json().get('data')
```

**Comment by Natetronn** [comment]
I saw your reply but, got distracted and forgot to come back to say thanks so, thanks again for sharing!
